- name: Install unbound
  apk:
    name:
      - unbound
    state: present
    update_cache: true

- name: Create /var/lib/unbound directory
  file:
    path: /var/lib/unbound
    state: directory
    owner: root
    group: unbound # unbound group needs write access to this directory
    mode: u=rwx,g=rwx,o=rx

- name: Download the list of root DNS servers
  get_url:
    url: https://www.internic.net/domain/named.cache
    dest: /var/lib/unbound/root.hints
    owner: root
    group: root

- name: Run unbound-anchor -a /var/lib/unbound/root.key to create root.key
  command: unbound-anchor -a /var/lib/unbound/root.key
  ignore_errors: yes # not sure what is happening with unbound-anchor returning a non zero value even after successful execution

- name: Create a cron job to update root.hints daily at midnight (0 0 * *)
  ansible.builtin.cron:
    name: "update /var/lib/unbound/root.hints"
    minute: "0"
    hour: "0"
    job: "wget https://www.internic.net/domain/named.cache -O /var/lib/unbound/root.hints"

- name: Generate unbound config
  template:
    src: "templates/unbound.conf"
    dest: "/etc/unbound/unbound.conf"
  notify: "reboot the server"

- name: Enable and start unbound service
  service:
    name: unbound
    enabled: yes
    state: started
  notify: "reboot the server"

- name: Delete the Network helper resolv.conf created by Linode. IMPORTANT! You must disable automatic configuration of networking before the next reboot, or this file will be re-written by Linode. (https://www.linode.com/docs/guides/network-helper/). Linode -> choose instance -> Configurations -> Edit -> Auto configure networking
  file:
    path: "/etc/resolv.conf"
    state: absent
  notify: "reboot the server"

# TODO: This needs further testing (run the whole playbook against a freshly
# re-imaged server)
#
# https://www.pcextreme.nl/community/d/94-unbound-local-dns-cache-on-ubuntu-and-centos
- name: Configure the system to use the local unbound DNS
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver'
    line: 'nameserver 127.0.0.1'
    create: yes
