- name: Update and upgrade apk. Update cache.
  community.general.apk:
    upgrade: yes
    update_cache: yes

- name: Upgrade kernel and headers
  community.general.apk:
    name:
      - linux-virt # kernel
      - linux-virt-dev # headers
    state: latest
  register: kernel_and_header

- name: Reboot to latest kernel if it was upgraded
  reboot:
    msg: Reboot by Ansible
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: kernel_and_header.changed

- name: Install WireGuard
  community.general.apk:
    name:
      - wireguard-tools
    state: latest
    update_cache: true
